name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia Ã  meia-noite (UTC)
  workflow_dispatch:      # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Gera os arquivos da snake em dist/
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: EduardoCarolinoSantos
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Publica a pasta dist na branch "output"
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
