name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # todo dia Ã  meia-noite (UTC)
  workflow_dispatch:        # permite rodar manualmente

permissions:
  contents: write           # permite o commit feito pelo action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: EduardoCarolinoSantos
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit Snake file
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "chore: update snake"
          add: "dist/*.svg"
